name: snapshot_plus
description: A library that can be used to implement data classes and simplifies conversion of JSON to data classes
version: 0.3.1
homepage: https://github.com/appsup-dart/snapshot

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.9.0
  intl: ^0.18.1
  meta: ^1.14.0
  collection: ^1.18.0
  quiver: ^3.2.1
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.3
